### ISSUE TITLE
希望能有clash版本的

### ISSUE THREAD

**Issue by 2584191127** [Barabama/FreeNodes#14]

**Comment by xfxssr** [comment]
支持V2Ray、vpn、免费机场、无限流量，免费VPN，无限流量！V2Ray节点分享，支持v2ray，clash，小火箭！vpn，winxray、2rayNG，BifrostV，Clash，Kitsunebi，V2rayN，V2rayW，Clash，V2rayS，Mellow，Qv2ray，v2ray，clash机场，科学上网翻墙白嫖节点，免费梯子，白嫖梯子，免费代理，永久免费代理https://github.com/xfxssr/FreeSSSSRV2RayClash
